name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Print python version
      run: |
        python --version 

    - name: Intall dotfiles
      run: |
        ./install
